// packages/sdk/template/src/app.tsx

/**
 * Main app configuration for the Auxx extension.
 *
 * This file exports:
 * 1. An `app` object that defines all surfaces (actions, widgets, etc.)
 * 2. An `App` component that provides the main UI for your extension
 */

import { TextBlock } from '@auxx/sdk/client'

/**
 * App configuration object.
 *
 * The app object organizes surfaces by their context (record, workflow, settings, etc.)
 * Each surface must include required fields: id, type, and location.
 */
export const app = {
  /**
   * Record-related surfaces (actions and widgets that work with records)
   */
  record: {
    /**
     * Actions that appear on individual records.
     *
     * These actions show up in the record detail view and can be triggered by users.
     * Each action must have:
     * - id: Unique identifier for the action
     * - label: User-facing text
     * - onTrigger: Function called when the action is clicked
     */
    actions: [],

    /**
     * Bulk actions that operate on multiple records at once.
     *
     * These appear in the record list view when multiple records are selected.
     */
    bulkActions: [],

    /**
     * Widgets that display custom content within record views.
     *
     * Widgets can show additional information or interactive UI elements.
     */
    widgets: [],
  },

  /**
   * Call recording-related surfaces (for analyzing call transcripts, summaries, and insights)
   */
  callRecording: {
    insight: {
      /**
       * Text selection actions for call recording insights
       */
      textActions: [],
    },
    summary: {
      /**
       * Text selection actions for call recording summaries
       */
      textActions: [],
    },
    transcript: {
      /**
       * Text selection actions for call recording transcripts
       */
      textActions: [],
    },
  },

  /**
   * Workflow-related surfaces (custom blocks that can be used in workflows)
   *
   * NEW FORMAT: Use flat arrays for blocks and triggers (recommended)
   * - blocks: Array of WorkflowBlock objects that perform actions
   * - triggers: Array of WorkflowTrigger objects that initiate workflows
   */
  workflow: {
    /**
     * Workflow blocks that perform actions within a workflow.
     * These appear in the workflow editor and can be dragged onto the canvas.
     */
    blocks: [],

    /**
     * Workflow triggers that initiate workflows based on events.
     * These define when and how workflows start executing.
     */
    triggers: [],
  },
}

/**
 * Main App Component
 *
 * This component is rendered by the Auxx platform in certain contexts like
 * the app's main page. The settings UI is automatically generated by the
 * platform from your app.settings.ts schema and displayed in the Settings tab.
 *
 * You can customize this component to show:
 * - Welcome message
 * - Status information
 * - Extension documentation
 * - Quick links or helpful information
 *
 * IMPORTANT: This must be a React component that can be rendered.
 */
export function App() {
  return (
    <>
      <TextBlock align="center">Notion</TextBlock>
      <TextBlock align="left">
        This extension demonstrates the various surfaces available in Auxx. Use the navigation to
        explore different features of your extension.
      </TextBlock>
    </>
  )
}
