// src/blocks/shopify/resources/constants.ts

export const RESOURCES = [
  { value: 'order', label: 'Order' },
  { value: 'product', label: 'Product' },
  { value: 'customer', label: 'Customer' },
  { value: 'customerAddress', label: 'Customer Address' },
  { value: 'variant', label: 'Product Variant' },
  { value: 'inventoryItem', label: 'Inventory Item' },
  { value: 'inventoryLevel', label: 'Inventory Level' },
  { value: 'metafield', label: 'Metafield' },
  { value: 'fulfillment', label: 'Fulfillment' },
  { value: 'draftOrder', label: 'Draft Order' },
  { value: 'collection', label: 'Collection' },
  { value: 'discount', label: 'Discount Code' },
] as const

export const OPERATIONS = {
  order: [
    { value: 'create', label: 'Create' },
    { value: 'delete', label: 'Delete' },
    { value: 'get', label: 'Get' },
    { value: 'getMany', label: 'Get Many' },
    { value: 'update', label: 'Update' },
  ],
  product: [
    { value: 'create', label: 'Create' },
    { value: 'delete', label: 'Delete' },
    { value: 'get', label: 'Get' },
    { value: 'getMany', label: 'Get Many' },
    { value: 'update', label: 'Update' },
  ],
  customer: [
    { value: 'create', label: 'Create' },
    { value: 'update', label: 'Update' },
    { value: 'get', label: 'Get' },
    { value: 'getMany', label: 'Get Many' },
    { value: 'delete', label: 'Delete' },
    { value: 'search', label: 'Search' },
  ],
  customerAddress: [
    { value: 'create', label: 'Create' },
    { value: 'update', label: 'Update' },
    { value: 'get', label: 'Get' },
    { value: 'getMany', label: 'Get Many' },
    { value: 'delete', label: 'Delete' },
    { value: 'setDefault', label: 'Set Default' },
  ],
  variant: [
    { value: 'create', label: 'Create' },
    { value: 'update', label: 'Update' },
    { value: 'get', label: 'Get' },
    { value: 'getMany', label: 'Get Many' },
    { value: 'delete', label: 'Delete' },
  ],
  inventoryItem: [
    { value: 'get', label: 'Get' },
    { value: 'getMany', label: 'Get Many' },
    { value: 'update', label: 'Update' },
  ],
  inventoryLevel: [
    { value: 'getMany', label: 'Get Many' },
    { value: 'set', label: 'Set' },
    { value: 'adjust', label: 'Adjust' },
    { value: 'connect', label: 'Connect' },
    { value: 'delete', label: 'Delete' },
  ],
  metafield: [
    { value: 'create', label: 'Create' },
    { value: 'update', label: 'Update' },
    { value: 'get', label: 'Get' },
    { value: 'getMany', label: 'Get Many' },
    { value: 'delete', label: 'Delete' },
  ],
  fulfillment: [
    { value: 'create', label: 'Create' },
    { value: 'update', label: 'Update Tracking' },
    { value: 'get', label: 'Get' },
    { value: 'getMany', label: 'Get Many' },
    { value: 'cancel', label: 'Cancel' },
  ],
  draftOrder: [
    { value: 'create', label: 'Create' },
    { value: 'update', label: 'Update' },
    { value: 'get', label: 'Get' },
    { value: 'getMany', label: 'Get Many' },
    { value: 'delete', label: 'Delete' },
    { value: 'complete', label: 'Complete' },
    { value: 'sendInvoice', label: 'Send Invoice' },
  ],
  collection: [
    { value: 'create', label: 'Create' },
    { value: 'update', label: 'Update' },
    { value: 'get', label: 'Get' },
    { value: 'getMany', label: 'Get Many' },
    { value: 'delete', label: 'Delete' },
    { value: 'addProduct', label: 'Add Product' },
    { value: 'removeProduct', label: 'Remove Product' },
  ],
  discount: [
    { value: 'create', label: 'Create' },
    { value: 'update', label: 'Update' },
    { value: 'get', label: 'Get' },
    { value: 'getMany', label: 'Get Many' },
    { value: 'delete', label: 'Delete' },
  ],
} as const

export const ALL_OPERATIONS = [
  { value: 'create', label: 'Create' },
  { value: 'delete', label: 'Delete' },
  { value: 'get', label: 'Get' },
  { value: 'getMany', label: 'Get Many' },
  { value: 'update', label: 'Update' },
  { value: 'search', label: 'Search' },
  { value: 'setDefault', label: 'Set Default' },
  { value: 'set', label: 'Set' },
  { value: 'adjust', label: 'Adjust' },
  { value: 'connect', label: 'Connect' },
  { value: 'cancel', label: 'Cancel' },
  { value: 'complete', label: 'Complete' },
  { value: 'sendInvoice', label: 'Send Invoice' },
  { value: 'addProduct', label: 'Add Product' },
  { value: 'removeProduct', label: 'Remove Product' },
] as const

export const VALID_OPERATIONS: Record<string, string[]> = {
  order: ['create', 'delete', 'get', 'getMany', 'update'],
  product: ['create', 'delete', 'get', 'getMany', 'update'],
  customer: ['create', 'update', 'get', 'getMany', 'delete', 'search'],
  customerAddress: ['create', 'update', 'get', 'getMany', 'delete', 'setDefault'],
  variant: ['create', 'update', 'get', 'getMany', 'delete'],
  inventoryItem: ['get', 'getMany', 'update'],
  inventoryLevel: ['getMany', 'set', 'adjust', 'connect', 'delete'],
  metafield: ['create', 'update', 'get', 'getMany', 'delete'],
  fulfillment: ['create', 'update', 'get', 'getMany', 'cancel'],
  draftOrder: ['create', 'update', 'get', 'getMany', 'delete', 'complete', 'sendInvoice'],
  collection: ['create', 'update', 'get', 'getMany', 'delete', 'addProduct', 'removeProduct'],
  discount: ['create', 'update', 'get', 'getMany', 'delete'],
}
