export const RESOURCES = [
  { value: 'message', label: 'Message' },
  { value: 'chat', label: 'Chat' },
  { value: 'callback', label: 'Callback' },
  { value: 'file', label: 'File' },
] as const

export const OPERATIONS = {
  message: [
    { value: 'sendMessage', label: 'Send Message' },
    { value: 'editMessageText', label: 'Edit Text' },
    { value: 'deleteMessage', label: 'Delete' },
    { value: 'pinMessage', label: 'Pin' },
    { value: 'unpinMessage', label: 'Unpin' },
    { value: 'sendChatAction', label: 'Send Chat Action' },
    { value: 'sendPhoto', label: 'Send Photo' },
    { value: 'sendDocument', label: 'Send Document' },
    { value: 'sendVideo', label: 'Send Video' },
    { value: 'sendAudio', label: 'Send Audio' },
    { value: 'sendAnimation', label: 'Send Animation' },
    { value: 'sendSticker', label: 'Send Sticker' },
    { value: 'sendLocation', label: 'Send Location' },
    { value: 'sendMediaGroup', label: 'Send Media Group' },
  ],
  chat: [
    { value: 'get', label: 'Get' },
    { value: 'getAdministrators', label: 'Get Administrators' },
    { value: 'getMember', label: 'Get Member' },
    { value: 'leave', label: 'Leave' },
    { value: 'setDescription', label: 'Set Description' },
    { value: 'setTitle', label: 'Set Title' },
  ],
  callback: [
    { value: 'answerQuery', label: 'Answer Query' },
    { value: 'answerInlineQuery', label: 'Answer Inline Query' },
  ],
  file: [{ value: 'get', label: 'Get' }],
} as const

export const ALL_OPERATIONS = [
  { value: 'answerInlineQuery', label: 'Answer Inline Query' },
  { value: 'answerQuery', label: 'Answer Query' },
  { value: 'deleteMessage', label: 'Delete' },
  { value: 'editMessageText', label: 'Edit Text' },
  { value: 'get', label: 'Get' },
  { value: 'getAdministrators', label: 'Get Administrators' },
  { value: 'getMember', label: 'Get Member' },
  { value: 'leave', label: 'Leave' },
  { value: 'pinMessage', label: 'Pin' },
  { value: 'sendAnimation', label: 'Send Animation' },
  { value: 'sendAudio', label: 'Send Audio' },
  { value: 'sendChatAction', label: 'Send Chat Action' },
  { value: 'sendDocument', label: 'Send Document' },
  { value: 'sendLocation', label: 'Send Location' },
  { value: 'sendMediaGroup', label: 'Send Media Group' },
  { value: 'sendMessage', label: 'Send Message' },
  { value: 'sendPhoto', label: 'Send Photo' },
  { value: 'sendSticker', label: 'Send Sticker' },
  { value: 'sendVideo', label: 'Send Video' },
  { value: 'setDescription', label: 'Set Description' },
  { value: 'setTitle', label: 'Set Title' },
  { value: 'unpinMessage', label: 'Unpin' },
] as const

export const VALID_OPERATIONS: Record<string, string[]> = {
  message: [
    'sendMessage',
    'editMessageText',
    'deleteMessage',
    'pinMessage',
    'unpinMessage',
    'sendChatAction',
    'sendPhoto',
    'sendDocument',
    'sendVideo',
    'sendAudio',
    'sendAnimation',
    'sendSticker',
    'sendLocation',
    'sendMediaGroup',
  ],
  chat: ['get', 'getAdministrators', 'getMember', 'leave', 'setDescription', 'setTitle'],
  callback: ['answerQuery', 'answerInlineQuery'],
  file: ['get'],
}
